apiVersion: apps/v1
kind: Deployment
metadata:
  name: demokuber-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: DemoKuber
  template:
    metadata:
      labels:
        app: DemoKuber
    spec:
      containers:
      - name: demokuberrepos
        image: sample714cr.azurecr.io/demokuberrepos:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: dsconfigsn

---
apiVersion: v1
kind: Service
metadata:
  name: demokuber
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: DemoKuber